### PR TITLE
Use nan to abstract away v8 API changes

### PR DESCRIPTION
**Pull request by jkrems**
Replaces direct access to node and v8 APIs by their nan equivalents.
This way the module compiles cleanly against both older versions of
v8 and the ones used in node 0.12 and io.js.

It also changes the `package.json` to specify a `test` script.
This way `npm i && npm t` work for this project which simplifies CI
integration.

See: https://github.com/rvagg/nan

### CODE REVIEW

**Comment by jkrems** [comment]
Passes on 0.8, 0.10, and iojs: https://travis-ci.org/jkrems/http-sync/builds/52196151

**Comment by jkrems** [comment]
There seems to be a possible error (access to `0xa0`) hidden in here somewhere. Investigating but it's pretty hard to reproduce (only happens on one version of Linux and under specific circumstances right now).

**Comment by dhruvbird** [comment]
Thanks for doing this!
Waiting on the resolution of the crash!

**Comment by jkrems** [comment]
The crash was caused by a custom libcurl as far as I can tell. Switching to a stock version of libcurl fixed the issue. So it doesn't look like it was actually caused by this code. Just took a bit to verify, sorry for the false alarm.

**Comment by jkrems** [comment]
Hi - sorry for the noise. Is there anything still blocking a merge? Just want to make sure we're not waiting on each other. :)

**Comment by dhruvbird** [comment]
Super! minor nit - please could you update version to 0.1.1 since this introduces new deps.
Good to merge!

**Comment by jkrems** [comment]
Sure thing! Done.

**Comment by dhruvbird** [comment]
I'm seeing some errors while running the test:

```
[dhruvbird ~/projects/http-sync] ~/bin/node-v0.10.20/bin/npm test

> http-sync@0.1.1 test /home/dhruvbird/projects/http-sync
> node test/index.js

1..6
not ok 1 - simpleGET
  SyntaxError: Unexpected token k while parsing kErrorAddressPrivate
      at Object.parse (native)
      at mkReq (/home/dhruvbird/projects/http-sync/test/index.js:22:21)
      at simpleGET (/home/dhruvbird/projects/http-sync/test/index.js:32:15)
      at /home/dhruvbird/projects/http-sync/test/index.js:75:7
      at Array.filter (native)
      at runTests [as _onTimeout] (/home/dhruvbird/projects/http-sync/test/index.js:73:22)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
not ok 2 - simplePOST
  SyntaxError: Unexpected token k while parsing kErrorAddressPrivate
      at Object.parse (native)
      at mkReq (/home/dhruvbird/projects/http-sync/test/index.js:22:21)
      at simplePOST (/home/dhruvbird/projects/http-sync/test/index.js:39:15)
      at /home/dhruvbird/projects/http-sync/test/index.js:75:7
      at Array.filter (native)
      at runTests [as _onTimeout] (/home/dhruvbird/projects/http-sync/test/index.js:73:22)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
.
.
.
ok 5 - externTLS
ok 6 - alwaysPass
```

**Comment by jkrems** [comment]
Interesting, I'm guessing that's a cross-platform problem..? I can't find any reference to `kErrorAddressPrivate` when googling. But since it seems to affect the local requests only, could you try changing it to `localhost` instead of `127.0.0.1`?

```js
options.host = options.host || 'localhost';
```

I tried running the tests on node 0.10.20 on my machine after a clean npm install and they passed.

**Comment by dhruvbird** [comment]
nvm, I think I know what's happening.

**Comment by dhruvbird** [comment]
Thanks for the changes - the code looks cleaner, and it's got better node support! :) 
Published to npm.
Tagged on github.

**Comment by jkrems** [comment]
Thanks for this project! Was definitely a big help in making `testium` happen. :)

**Comment by dhruvbird** [comment]
One more minor nit. You haven't added yourself to contributors in
package.json
It would be super if you could do that!
Thanks again!


On Thu, Mar 5, 2015 at 10:07 AM, Jan Olaf Krems <notifications@github.com>
wrote:

> Thanks for this project! Was definitely a big help in making testium
> happen. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhruvbird/http-sync/pull/35#issuecomment-77416165>.
>



-- 
   -Dhruv Matani.

"I was a Prisoner of Gravity"
-- Arthur Boorman

**Comment by jkrems** [comment]
Gladly, opened a second PR for that.

**Pull request merged**
