### PR TITLE
Upgrade nan to 2.x

### PR DESCRIPTION
**Pull request by hybrist**
This switches `nan` to 2.x. Mostly find/replace to switch to the namespaced function names and to append all the `.ToLocalChecked` calls. Using `nan@2.x` means that it should be compatible with both iojs 3.x and the upcoming node 4.0.0.

Tested (all on OSX):
- `nvm use 0.8 && npm i && npm test`
- `nvm use 0.10 && npm i && npm test`
- `nvm use iojs-v1 && npm i && npm test`
- `nvm use iojs-v2 && npm i && npm test`
- `nvm use iojs-v3 && npm i && npm test`

Also tested running an actual testium integration test suite on 0.10 and iojs v2 against this package and it passed. Which ran on a Linux box.

### CODE REVIEW

**Comment by dhruvbird** [comment]
Any chance you can bump up the version number so that I can publish a new npm.
Thx!
Also, update contributors list.

**Comment by hybrist** [comment]
Will do. I'm also about to give it some (limited) testing on Linux. Just to make sure. :)

**Comment by hybrist** [comment]
Done: Bumped the version. Contributors already had my name.

**Comment by hybrist** [comment]
@dhruvbird Sorry for the ping - node 4.0.0 is imminent. Do you have an estimate when this will be released? :)

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by rjyamada** [comment]
@dhruvbird any idea when this will be released?

**Comment by ghost** [comment]
_bump_ http-sync and node 4 should be besties!  Could you merge & publish? :smiley:

**Comment by quasipedia** [comment]
_bump_ :)

**Comment by paraplexed** [comment]
bump

**Comment by orzFly** [comment]
bump ;)

**Comment by NameFILIP** [comment]
will this be merged?

**Comment by spoon1312** [comment]
any update on this ?

**Comment by archgrove** [comment]
Another ping to beg for merge.

**Comment by fernandopasik** [comment]
this is really needed!!

**Comment by tstordyallison** [comment]
Any update on this one?!

**Comment by hybrist** [comment]
It doesn't look like the maintainer of this package has been active in the past year. So I'm going to go ahead and close this. If anybody needs this, the most likely path to success would be to fork and publish.

**Pull request closed without merging**
